### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Offirmo** [720kb/checked.css#2]
In chrome latest, whatever I choose with the select, I always have the "boing" items...

**Comment by 45kb** [comment]
Hi @Offirmo  there was a jquery bug for safari but on chrome looks really ok, can you please retry and tell me if anything still not working.

Which OS are you on?

Thank you 👍

**Comment by Offirmo** [comment]
Works this morning !

Your animations are fun :-)

**Comment by 45kb** [comment]
Thanks @Offirmo glad if you enjoy them 👍
